### ISSUE TITLE
extension failed on install

### ISSUE THREAD

**Issue by rudyvogt** [jamesqquick/Web-Development-Essentials-Extension-Pack#1]
Hi,

"robertohuertasm.vscode-icons" failed on install, it seems to be replaced by **vscode-icons-team.vscode-icons**

**Comment by jamesqquick** [comment]
Great catch! Updating now!

**Comment by jamesqquick** [comment]
Changes reflected in master branch. Latest extension file is being verified now.

**Comment by rudyvogt** [comment]
Hi James,

also the link in the readme - also need to be updated
VS Code Icons
https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons

ok i have notice that it redirects correctly - so no big issue

https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons

Rudy

**Comment by jamesqquick** [comment]
Yep, again great catch! I updated the link in the readme.
